# Generated by Django 5.2.6 on 2025-10-02 18:09

import django.db.models.deletion
"""
Migración para el modelo Patient.

Agrega la tabla de pacientes al sistema hospitalario.

.. moduleauthor:: enridami
"""
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=50, verbose_name='Apellido')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('identification_type', models.CharField(choices=[('DNI', 'DNI'), ('Passport', 'Pasaporte'), ('License', 'Licencia de Conducir'), ('Other', 'Otro')], default='DNI', max_length=20, verbose_name='Tipo de Identificación')),
                ('identification_number', models.CharField(max_length=50, unique=True, verbose_name='Número de Identificación')),
                ('gender', models.CharField(choices=[('Male', 'Masculino'), ('Female', 'Femenino'), ('Other', 'Otro')], max_length=10, verbose_name='Género')),
                ('date_of_birth', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('address_line', models.CharField(max_length=200, verbose_name='Dirección')),
                ('city', models.CharField(max_length=50, verbose_name='Ciudad')),
                ('region', models.CharField(max_length=50, verbose_name='Región/Estado')),
                ('postal_code', models.CharField(max_length=20, verbose_name='Código Postal')),
                ('country', models.CharField(default='Paraguay', max_length=50, verbose_name='País')),
                ('blood_type', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-'), ('Unknown', 'Desconocido')], default='Unknown', max_length=10, verbose_name='Tipo de Sangre')),
                ('allergies', models.TextField(blank=True, null=True, verbose_name='Alergias')),
                ('medical_notes', models.TextField(blank=True, null=True, verbose_name='Notas Médicas')),
                ('emergency_contact_name', models.CharField(max_length=100, verbose_name='Nombre del Contacto de Emergencia')),
                ('emergency_contact_relationship', models.CharField(max_length=50, verbose_name='Relación del Contacto')),
                ('emergency_contact_phone', models.CharField(max_length=20, verbose_name='Teléfono del Contacto de Emergencia')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('assigned_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.doctor', verbose_name='Doctor Asignado')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'ordering': ['-created_at'],
            },
        ),
    ]
