# Generated by Django 5.2.6 on 2025-10-02 18:11

"""
Migración para modificar el tipo de identificación del paciente.

.. moduleauthor:: enridami
"""
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='identification_type',
            field=models.CharField(choices=[('CI', 'CI'), ('DNI', 'DNI'), ('Passport', 'Pasaporte'), ('License', 'Licencia de Conducir'), ('Other', 'Otro')], default='DNI', max_length=20, verbose_name='Tipo de Identificación'),
        ),
    ]
