# Generated by Django 5.2.6 on 2025-11-04 14:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_patient_identification_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='emergency_contact_phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^\\+?\\d{7,15}$', message='Ingrese un número de teléfono válido (solo dígitos, opcional "+" al inicio).')], verbose_name='Teléfono del Contacto de Emergencia'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^\\+?\\d{7,15}$', message='Ingrese un número de teléfono válido (solo dígitos, opcional "+" al inicio).')], verbose_name='Teléfono'),
        ),
    ]
