# Generated by Django 5.2.6 on 2025-11-11 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_patient_emergency_contact_phone_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consultation',
            options={'ordering': ['time'], 'verbose_name': 'Consulta', 'verbose_name_plural': 'Consultas'},
        ),
    ]
