# Generated by Django 5.2.6 on 2025-10-09 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_patient_identification_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('time', models.TimeField(verbose_name='Hora')),
                ('shift', models.CharField(choices=[('MAÑANA', 'Mañana'), ('TARDE', 'Tarde'), ('NOCHE', 'Noche')], default='MAÑANA', max_length=10, verbose_name='Turno')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Orden')),
                ('priority', models.CharField(choices=[('NIVEL I', 'Nivel i'), ('Nivel II', 'Nivel ii'), ('Nivel III', 'Nivel iii'), ('Nivel IV', 'Nivel iv'), ('Nivel V', 'Nivel v')], default='Nivel IV', max_length=10, verbose_name='Prioridad')),
                ('status', models.CharField(choices=[('EN_ESPERA', 'En espera'), ('ATENDIDA', 'Atendida'), ('CANCELADA', 'Cancelada')], default='EN_ESPERA', max_length=15, verbose_name='Estado')),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.doctor', verbose_name='Médico')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.patient', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Consulta',
                'verbose_name_plural': 'Consultas',
                'ordering': ['-date', '-time'],
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication', models.CharField(max_length=100, verbose_name='Medicamento')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.consultation', verbose_name='Consulta')),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.doctor', verbose_name='Médico')),
            ],
            options={
                'verbose_name': 'Receta',
                'verbose_name_plural': 'Recetas',
                'ordering': ['-id'],
            },
        ),
    ]
