# Generated by Django 5.2.6 on 2025-10-10 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_consultation_prescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='status',
            field=models.CharField(choices=[('EN ESPERA', 'En espera'), ('ATENDIDO', 'Atendido'), ('CANCELADA', 'Cancelada')], default='EN ESPERA', max_length=15, verbose_name='Estado'),
        ),
    ]
