# Generated by Django 5.2.6 on 2025-10-10 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_consultation_circunferencia_abdominal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='circunferencia_abdominal',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='consultorio',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='evolucion',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='frecuencia_respiratoria',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='hba1c',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='historia_actual',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='impresion_diagnostica',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='indicaciones',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='peso',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='presion_diastolica',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='presion_sistolica',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='pulso',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='saturacion_oxigeno',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='talla',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='temperatura',
            field=models.FloatField(default=0),
        ),
    ]
