# Generated by Django 5.2.6 on 2025-10-11 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_consultation_circunferencia_abdominal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='circunferencia_abdominal',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='frecuencia_respiratoria',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='hba1c',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='peso',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='presion_diastolica',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='presion_sistolica',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='pulso',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='saturacion_oxigeno',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='talla',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='temperatura',
            field=models.FloatField(),
        ),
    ]
