# Generated by Django 5.2.6 on 2025-10-11 17:23

import django.db.models.deletion
"""
Migración para modificar campos en consulta médica.

.. moduleauthor:: enridami
"""
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_consultation_circunferencia_abdominal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='circunferencia_abdominal',
            field=models.FloatField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='evolucion',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='frecuencia_respiratoria',
            field=models.IntegerField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='hba1c',
            field=models.FloatField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='historia_actual',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='impresion_diagnostica',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='indicaciones',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='peso',
            field=models.FloatField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='presion_diastolica',
            field=models.IntegerField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='presion_sistolica',
            field=models.IntegerField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='pulso',
            field=models.IntegerField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='saturacion_oxigeno',
            field=models.IntegerField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='servicio',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.specialty'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='talla',
            field=models.FloatField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='temperatura',
            field=models.FloatField(blank=True, default='', null=True),
        ),
    ]
