# Generated by Django 5.2.6 on 2025-10-11 18:03

"""
Migración para agregar campo consultorio al modelo Doctor.

.. moduleauthor:: enridami
"""
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_consultation_circunferencia_abdominal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='consultorio',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
