# Generated by Django 5.2.6 on 2025-10-13 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_doctorschedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='consultorio',
        ),
    ]
